-- 코드를 입력하세요
SELECT date_format(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
WHERE sales_date like '2022-03%'
union all
SELECT date_format(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,PRODUCT_ID, NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE sales_date like '2022-03%'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID