-- 코드를 입력하세요
SELECT A.REST_ID REST_ID, A.REST_NAME REST_NAME, A.FOOD_TYPE FOOD_TYPE, A.FAVORITES FAVORITES, A.ADDRESS ADDRESS
,ROUND(AVG(B.REVIEW_SCORE),2) score
FROM REST_INFO A, REST_REVIEW B
WHERE A.REST_ID = B.REST_ID AND ADDRESS LIKE '서울%'
GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
