-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE SUBSTR(TO_CHAR(DATE_OF_BIRTH),4,3) = 'MAR'
AND TLNO IS NOT NULL 
AND GENDER = 'W'
ORDER BY MEMBER_ID
