-- 코드를 입력하세요
SELECT A.MEMBER_NAME MEMBER_NAME, B.REVIEW_TEXT REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE,'YYYY-mm-dd') REVIEW_DATE
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID AND A.MEMBER_ID = (SELECT MEMBER_ID FROM (SELECT A.MEMBER_ID MEMBER_ID
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
GROUP BY A.MEMBER_ID
ORDER BY COUNT(*) DESC)
WHERE ROWNUM = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT