-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) MONTHS, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE SUBSTR(TO_CHAR(START_DATE,'YYYY-MM-DD'),1,7) BETWEEN '2022-08' AND'2022-10'
AND CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
              GROUP BY CAR_ID
              HAVING COUNT(*)>4)
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTHS, CAR_ID DESC